[project]
name = "myblog-third"
version = "0.1.0"
description = "Add a short description here"
authors = [
    { name = "sasakiy84" }
]
dependencies = [
    "mkdocs-material>=9.1.17",
    "mkdocs-blogging-plugin>=2.2.9",
]
readme = "README.md"
requires-python = ">= 3.8"
